### ISSUE TITLE
Missing AI verify buton?!

### ISSUE THREAD

**Issue by ondraman** [noodlapp/noodl#19] opened 2024-02-02 00:26 UTC
![Snímek obrazovky 2024-02-02 012334](https://github.com/noodlapp/noodl/assets/13682293/c64be859-16f5-493b-ba09-63a17b0931ea)
Reality
![Snímek obrazovky 2024-02-02 012511](https://github.com/noodlapp/noodl/assets/13682293/8698758d-1853-4e9b-b957-ece9cf9afab3)
Documentation

**Comment by michaelcartner** [comment] 2024-02-02 08:20
Duplicate of #13 

This has been fixed, but no new release has been built yet.
To get the fix now you can try building from source.

**Closed by michaelcartner** 2024-02-02 08:20 UTC
